disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace

force_try:
  severity: warning # explicitly
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods